import {MovieSearchResponse} from '../../src/types/responses/v3/MovieSearchResponse';

export const searchResult: MovieSearchResponse = {
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: '/jGyIsNQBQ17G92ZxuTErrMl6W1e.jpg',
			genre_ids: [27, 28, 14],
			id: 22894,
			original_language: 'en',
			original_title: 'Legion',
			overview:
				"When God loses faith in humankind, he sends his legion of angels to bring on the Apocalypse. Humanity's only hope for survival lies in a group of strangers trapped in an out-of-the-way, desert diner with the Archangel Michael.",
			popularity: 63.534,
			poster_path: '/ykocDqwg5PRUopnBVb1x1DWnEJF.jpg',
			release_date: '2010-01-21',
			title: 'Legion',
			video: false,
			vote_average: 5.826,
			vote_count: 2360,
		},
		{
			adult: false,
			backdrop_path: '/pUG4A0oT6k1BYQG9nxfQ78sGnvO.jpg',
			genre_ids: [28, 878],
			id: 45326,
			original_language: 'en',
			original_title: 'Legion',
			overview: 'This future-set sci-adventure follows a band of brave soldiers in an epic battle against a government-created monster.',
			popularity: 4.632,
			poster_path: '/9ro4BujCD9aFaTI1YMH76Fj9Fgr.jpg',
			release_date: '1998-04-18',
			title: 'Legion',
			video: false,
			vote_average: 3.3,
			vote_count: 11,
		},
		{
			adult: false,
			backdrop_path: '/aTuUUmLWK3JIKUhplm8iQPhVRn5.jpg',
			genre_ids: [27, 53, 9648],
			id: 1020237,
			original_language: 'en',
			original_title: 'Legion',
			overview:
				"(Fan edit of Exorcist 3)  A reworking of EXORCIST III in line with LEGION, the low key and more character-driven film that William Peter Blatty originally shot before studio-enforced reshoots and renaming. This edit restores the original cut's story arc, sans exorcist and exorcism, and includes a recreation of the original ending as described by Blatty.",
			popularity: 1.446,
			poster_path: '/eYduYEFcoWovd3Oh3dSlfWZs0Kz.jpg',
			release_date: '2016-10-25',
			title: 'Legion',
			video: false,
			vote_average: 7.25,
			vote_count: 4,
		},
		{
			adult: false,
			backdrop_path: '/bDBBjhkHAXQhfSuhdrh4MdpjSfC.jpg',
			genre_ids: [27, 53, 14, 35],
			id: 709195,
			original_language: 'es',
			original_title: 'Legiones',
			overview:
				'While evil forces descend on Argentina, humanity’s best hope, a once-legendary shaman is confined to an insane asylum, powerless to avert the demonic resurrection.',
			popularity: 7.891,
			poster_path: '/9bpmojZqoclbXGcsG2VJq4GOWa3.jpg',
			release_date: '2022-04-15',
			title: 'Legions',
			video: false,
			vote_average: 7,
			vote_count: 26,
		},
		{
			adult: false,
			backdrop_path: '/vGKK5i8RTMhvuCUciEalq86otkt.jpg',
			genre_ids: [36, 28, 12],
			id: 308695,
			original_language: 'en',
			original_title: 'The Lost Legion',
			overview: 'Following the fall of the Roman Empire, a Roman woman plots to make her son the new Emperor and to fulfill the former glory of the city.',
			popularity: 6.561,
			poster_path: '/gvgvgR3H7DLUnGVipEsYUKsmALe.jpg',
			release_date: '2014-12-02',
			title: 'The Lost Legion',
			video: false,
			vote_average: 6.045,
			vote_count: 33,
		},
		{
			adult: false,
			backdrop_path: '/jhi3K0rN46SSu9wEu6zYVCOeVtH.jpg',
			genre_ids: [16, 28, 878],
			id: 1003580,
			original_language: 'en',
			original_title: 'Legion of Super-Heroes',
			overview:
				'Kara, devastated by the loss of Krypton, struggles to adjust to her new life on Earth. Her cousin, Superman, mentors her and suggests she leave their space-time to attend the Legion Academy in the 31st century, where she makes new friends and a new enemy: Brainiac 5. Meanwhile, she must contend with a mysterious group called the Dark Circle as it searches for a powerful weapon held in the Academy’s vault.',
			popularity: 40.178,
			poster_path: '/8M6bA5t2q5u1nWDTEIXuGDwvboW.jpg',
			release_date: '2023-02-07',
			title: 'Legion of Super-Heroes',
			video: false,
			vote_average: 6.463,
			vote_count: 135,
		},
		{
			adult: false,
			backdrop_path: '/r3j0VCyDTHcKqhovRkY31Ks3OtP.jpg',
			genre_ids: [18, 36, 10752],
			id: 622585,
			original_language: 'pl',
			original_title: 'Legiony',
			overview:
				'A universal story about entering adulthood in difficult times, growing up to the community. The great history is the background for the love story unfolding in the foreground: Józek, a deserter from the tsaarist army who joins the emerging LLegions, an intelligence agent for the I Brigade and Women’s Leage member – Ola, and Tadek, her fiancée, a member of Shooting Team.',
			popularity: 4.412,
			poster_path: '/ru4iaK4G8TraFyGRECQbUgxN7Ty.jpg',
			release_date: '2019-10-12',
			title: 'The Legions',
			video: false,
			vote_average: 6.652,
			vote_count: 33,
		},
		{
			adult: false,
			backdrop_path: '/djYdwKV7u1Zu0UlscE6V0ab3Cxz.jpg',
			genre_ids: [28, 18],
			id: 846800,
			original_language: 'it',
			original_title: 'Il legionario',
			overview:
				'Daniel is the only African-Italian officer in the flying squad in Rome, tasked with evicting 150 families from an apartment building that they have taken over. One of the families is his own.',
			popularity: 1.824,
			poster_path: '/lgdPNBevqZqV60zztJbd86u7YoL.jpg',
			release_date: '2022-02-24',
			title: 'The Legionnaire',
			video: false,
			vote_average: 5.118,
			vote_count: 17,
		},
		{
			adult: false,
			backdrop_path: '/75f1G6yTzTPDzt3eambWX35iLzz.jpg',
			genre_ids: [36, 18, 12],
			id: 168479,
			original_language: 'it',
			original_title: 'Le legioni di Cleopatra',
			overview:
				'Octavio secretly sent his consul Curridio to Alexandria in a final attempt to reach peace. In the city, he meets Berenice, a mysterious and beautiful dancer who falls in love. Actually, the dancer is the queen Cleopatra who leads a double life using this name.',
			popularity: 1.382,
			poster_path: '/koH2d6vCEdgFiRcZgk2kgpKqyeB.jpg',
			release_date: '1959-11-27',
			title: 'Legions of the Nile',
			video: false,
			vote_average: 5.2,
			vote_count: 5,
		},
		{
			adult: false,
			backdrop_path: '/qICwuWu8EB2Nl3usiiHM0TvvInd.jpg',
			genre_ids: [18, 10752],
			id: 206725,
			original_language: 'es',
			original_title: '¡A mí la Legión!',
			overview:
				'In North Africa, in a detachment of the Spanish Legion, el Grajo, a brave veteran, and Mauro, who has just enlisted, become close friends. When an unfortunate circumstance results in the death of a man, suspicions fall on one of them.',
			popularity: 1.597,
			poster_path: '/6KD88H8E8pYBh6cidFJU2qiLeF1.jpg',
			release_date: '1942-05-11',
			title: 'Follow the Legion!',
			video: false,
			vote_average: 5,
			vote_count: 6,
		},
		{
			adult: false,
			backdrop_path: '/1ve1TMFBha5Pbp1T81Ro01DmYXh.jpg',
			genre_ids: [14, 878, 27],
			id: 59480,
			original_language: 'ja',
			original_title: 'ガメラ2 レギオン襲来',
			overview:
				'A strange meteor lands in Japan and unleashes hundreds of insect-like "Legion" creatures bent on colonizing the Earth. When the military fails to control the situation, Gamera shows up to deal with the ever-evolving space adversary. However the battle may result in Gamera losing his bond with both Asagi and humanity.',
			popularity: 9.204,
			poster_path: '/xPBtoCLUN0raEKywuiSId6SSRAc.jpg',
			release_date: '1996-07-12',
			title: 'Gamera 2: Attack of Legion',
			video: false,
			vote_average: 7.559,
			vote_count: 94,
		},
		{
			adult: false,
			backdrop_path: '/9NlswPRK5Kap6KVr59Feah9EBLP.jpg',
			genre_ids: [12, 36, 28],
			id: 631939,
			original_language: 'en',
			original_title: 'The Legion',
			overview:
				'Noreno, a half-Roman, is entrusted with the mission of crossing the snowy mountains of Armenia, swarming with Parthian patrols, to seek help for his slowly dying men.',
			popularity: 12.867,
			poster_path: '/1kiCqFizPPpULUR1YhAkp8bO9Jo.jpg',
			release_date: '2020-05-08',
			title: 'The Legion',
			video: false,
			vote_average: 6.077,
			vote_count: 104,
		},
		{
			adult: false,
			backdrop_path: '/tgaMo8q1HpGTbtpmJm8TYKTpOr4.jpg',
			genre_ids: [28, 12, 14, 10752],
			id: 9703,
			original_language: 'en',
			original_title: 'The Last Legion',
			overview:
				'As the Roman empire crumbles, young Romulus Augustus flees the city and embarks on a perilous voyage to Britain to track down a legion of supporters.',
			popularity: 16.378,
			poster_path: '/k2jaEoOsTEMqSskBJm3gfcuxNEc.jpg',
			release_date: '2007-04-19',
			title: 'The Last Legion',
			video: false,
			vote_average: 5.613,
			vote_count: 736,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [12, 18],
			id: 561015,
			original_language: 'it',
			original_title: 'Legione straniera',
			overview: '',
			popularity: 0.6,
			poster_path: '/cyzT7N5vBkCjAaN0NjYKz7AnFc2.jpg',
			release_date: '1953-08-27',
			title: 'Trouble for the Legion',
			video: false,
			vote_average: 5,
			vote_count: 2,
		},
		{
			adult: false,
			backdrop_path: '/5XNEf3tYfKuu1nHlqffdoyiXCtQ.jpg',
			genre_ids: [16, 28, 12, 10751, 35],
			id: 353595,
			original_language: 'en',
			original_title: 'LEGO DC Comics Super Heroes: Justice League - Attack of the Legion of Doom!',
			overview:
				"Crime is on the run as the newly formed Justice League keeps Metropolis safe and this makes evil genius Lex Luthor very unhappy. Together with Black Manta, Sinestro and a gang of ruthless recruits, Lex builds his own league and declares them the Legion of Doom. With this super powered team of terror and a plan to attack the top-secret government site, Area 52, can Lex finally be on the verge of victory? Sound the alarm and get ready for the bricks to fly when Superman, Batman, Wonder Woman and the rest of the Justice League face off against the world's greatest Super-Villains! It's the next all-new original movie from LEGO® and DC Comics.",
			popularity: 14.639,
			poster_path: '/x7RowYDdokZgb8yW2cAlOS70JiK.jpg',
			release_date: '2015-08-25',
			title: 'LEGO DC Comics Super Heroes: Justice League - Attack of the Legion of Doom!',
			video: false,
			vote_average: 6.963,
			vote_count: 108,
		},
		{
			adult: false,
			backdrop_path: '/9EC2h6vT9P5RX8grIfIclFjWfWX.jpg',
			genre_ids: [],
			id: 475878,
			original_language: 'it',
			original_title: 'Il legionario',
			overview:
				'Daniel is the son of African parents born in Rome. He is a police officer of the State Police Department. One day he finds out that his unit will have to clear a building where his mother and brother live. Torn between the love for his family and the loyalty to the police, Daniel will have to choose between the two and go with it until the end.',
			popularity: 0.6,
			poster_path: '/7aQCZNCt6XxQvGl4wzX0BJyhjLW.jpg',
			release_date: '2017-09-01',
			title: 'The Legionnaire',
			video: false,
			vote_average: 0,
			vote_count: 0,
		},
		{
			adult: false,
			backdrop_path: '/gJIb1Q5zUYW1GpmgpXZgAaLKE5G.jpg',
			genre_ids: [35],
			id: 95658,
			original_language: 'fr',
			original_title: 'Un de la légion',
			overview:
				"Fernand Espitalion is miserable as totally whipped husband of a dragon 'passed on' -like cloths- by his late cousin. She often leaves him waiting outside like a dog when she does business. While she sees a notary about an inheritance, he's seduced to a bar by a shady man. The rogue gets Fernand drunk, knocks him out and switches costumes and papers. He's now Robert Durand, a voluntary Foreign legion recruit. After failed attempts to explain, he tastes military life and finds it less disciplined and more enjoyable then, marriage. But will that last when his wife tracks him and his unit is sent to action in tribal Algeria?",
			popularity: 0.931,
			poster_path: '/ai6VnTAbEkUOVZ8IOXe0obuRdRJ.jpg',
			release_date: '1936-10-02',
			title: 'One of the Legion',
			video: false,
			vote_average: 6,
			vote_count: 3,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [],
			id: 538499,
			original_language: 'fr',
			original_title: "Légions d'honneur",
			overview: 'An officer is tried for self-inflicted injury.He is thrown out of the Foreign Legion .',
			popularity: 1.4,
			poster_path: '/wOr0qWvp2mA98ICo7ZZPV7SfBqm.jpg',
			release_date: '1938-02-17',
			title: 'Legions of Honor',
			video: false,
			vote_average: 0,
			vote_count: 0,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [35],
			id: 1023581,
			original_language: 'hu',
			original_title: 'A pesti légionárius',
			overview: 'An entertaining compilation of cabaret scenes by Jenő Rejtő, accompanied by contemporary chansons.',
			popularity: 0.6,
			poster_path: null,
			release_date: '1994-01-01',
			title: 'The Pest Legionnaire',
			video: true,
			vote_average: 0,
			vote_count: 0,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [18],
			id: 607235,
			original_language: 'pl',
			original_title: 'Legion ulicy',
			overview: "Józek enters a cycling race to win a bike, which he needs to deliver newspapers and pay for his mother's surgery.",
			popularity: 0.621,
			poster_path: '/1RAY80vacMtpAOKTnuajTBvhugM.jpg',
			release_date: '1932-03-18',
			title: 'Legion of the Streets',
			video: false,
			vote_average: 5,
			vote_count: 1,
		},
	],
	total_pages: 9,
	total_results: 176,
};
